blank_issues_enabled: false
contact_links:
  - name: Report a security problem
    url: https://github.com/tolokacode/.github/blob/main/SECURITY.md
    about: Please report security problems privately, not in a public issue.
